# Generated by Django 2.0 on 2018-01-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('givvy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='givvy.User')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
