# Generated by Django 2.0 on 2018-01-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mattermost_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('heart', models.IntegerField(default=0)),
                ('quota', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='givvy.User'),
        ),
    ]
